### ISSUE TITLE
Ordenar Alfabeticamente

### ISSUE THREAD

**Issue by matbrgz** [laryssamagalhaes/pessoas-palestrantes#31]
Seria interessante dividir os palestrantes por estado e ordenar os nomes alfabeticamente, o que acham?

**Comment by laryssamagalhaes** [comment]
Seria interessante mesmo, já estava com isso em mente mesmo! Obrigada por reportar :)

**Comment by brunopulis** [comment]
@laryssamagalhaes posso te ajudar nessa ordenação?

**Comment by laryssamagalhaes** [comment]
Claro @brunopulis fique a vontade <3

**Comment by laryssamagalhaes** [comment]
@brunopulis @MatheusRV Oi gente :) 

Eu alterei um pouco o projeto e agora o Readme é criado automaticamente através de um script node a cada merge na master, já ordenado e organizado por cidades - estado 💯 . Obrigada pelo feedback!

**Comment by brunopulis** [comment]
@laryssamagalhaes acho que isso vai ser útil pra eu usar no Awesome A11y obrigado :)
