### ISSUE TITLE
(:

### ISSUE THREAD

**Issue by troyam** [laryssamagalhaes/pessoas-palestrantes#62]
`{
                                                                "name": "Marcos Porto",
                                                                "location": "Belo Horizonte",
                                                                "subjects": [
                                                                    "Front-end",
                                                                    "React",
                                                                    "React Native",
                                                                    "MySQL",
                                                                    "PHP",
                                                                    "HTML5",
                                                                    "NodeJS - Node+JS from Interactive North America",
                                                                    "Angular",
                                                                    "CSS",
                                                                    "JavaScript",
                                                                    "jQuery",
                                                                    "SQL",
                                                                    "Mongodb",
                                                                    "Websockets',
                                                                    "Artificial Intelligence (AI)",
                                                                    "Virtual Machines",
                                                                    "Synaptic and Natural",
                                                                    "Kali-Linux",
                                                                    "Blockchain - Cryptocurrency and Company Analysis"
                                                                ],
                                                                "socials": [ // links para entrar em contato
                                                                    "[github](https://github.com/troyam)",
                                                                    "[medium](https://medium.com/@marcosporto99)",
                                                                    "[instagram](https://instagram.com/_mporto)"
                                                                ]
                                                            }`

**Comment by laryssamagalhaes** [comment]
Oi @troyam acho que vc não entendeu mt bem sobre abrir um PR para inserir tais informações. 

De qualquer forma, não tem problema eu posso abrir um inserindo suas informações
